### ISSUE TITLE
Add Support for Symfony 7.0

### ISSUE THREAD

**Issue by rcournault** [bpolaszek/webpush-bundle#49]
Can you update this project for Symfony 7.0 / 7.1 please ?

**Comment by encreinformatique** [comment]
Just to add information to this issue.

One of the changes would be in the [command file](https://github.com/bpolaszek/webpush-bundle/blob/master/src/Command/WebPushGenerateKeysCommand.php), using the [`AsCommand` attribute](https://github.com/symfony/console/blob/5.3/Attribute/AsCommand.php) of the console component. It has been introduced in 5.3.
Supporting Symfony 7.0 would mean dropping support for versions prior to 5.2, let's say prior to 5.4. (LTS version) Otherwise we cannot drop the `$publicName` property hence the deprecation remains.
I did not verify the other possible deprecations yet.

I started to "clean" the versions of a some dependencies in [that PR](https://github.com/bpolaszek/webpush-bundle/pull/50/files).

@bpolaszek has probably more to add to this.
